# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=150)),
            ],
        ),
    ]
